import json
from watch import Watch, Collection
from datetime import date, timedelta, datetime, timezone

if __name__ == "__main__":
    # my_vault = Collection()
    # watch1 = Watch("Seiko", "Selection", "SBTM325")
    # watch2 = Watch("Seiko", "A904 5199")
    # my_vault.add(watch1)
    # my_vault.add(watch2)
    # watch4 = Watch("Citizen", "Garison", movement_type="Quartz", ref_no='BM8180-03E', accuracy_sec_month=15)
    # watch4.last_reset_date = date.today() - timedelta(days=10)
    # watch4.log_drift(2, as_of=date.today() - timedelta(days=7))
    # watch4.log_drift(4, as_of=date.today() - timedelta(days=4))
    # watch4.log_drift(4, as_of=date.today() - timedelta(days=3))
    # watch4.log_drift(5, as_of=date.today() - timedelta(days=1))
    # my_vault.add(watch4)
    # watch4.reset()
    # watch4.log_drift(1, as_of=date.today() + timedelta(days=1))
    # watch4.log_drift(2, as_of=date.today() + timedelta(days=2))
    # watch4.log_drift(3, as_of=date.today() + timedelta(days=3))
    # print(watch4.health_score())
    # print(watch4.health_score(1))
    # my_vault.export_to_json()
    # my_vault.show_collection()
    # my_vault.collection_health()
    vault = Collection()
    vault.load_from_json()
    # vault.show_collection()
    my_citi = vault.find_ref_no('BM8180-03E')
    my_citi.log_drift(4, as_of=date.today() + timedelta(days=8))
    my_citi.log_drift(4, as_of=date.today() + timedelta(days=6))
    # my_citi.log_drift(5)
    # vault.collection_health()
    # vault.find_ref_no('SBTM325')
    # vault.export_to_txt()
    # vault.collection_health()
    my_citi.reset()
    my_citi.log_drift(1, as_of=datetime.now(timezone.utc) + timedelta(days=1))
    my_citi.log_drift(1.5, as_of=datetime.now(timezone.utc) + timedelta(days=2))
    my_citi.log_drift(2, as_of=datetime.now(timezone.utc) + timedelta(days=3))
    my_citi.log_drift(2.5, as_of=datetime.now(timezone.utc) + timedelta(days=4))
    my_citi.log_drift(3.1, as_of=datetime.now(timezone.utc) + timedelta(days=5))
    print(my_citi.health_score())
